#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 28 08:57:56 2020

@author: krutheekarajkumar
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_dataset = ImageDataGenerator(1./255)

# instantiate the ImageDataGenerator object
train_dataset.flow_from_directory(train_dir)